[package]
name = "vtuber-avatar"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "Bevy and bevy_vrm1 adapter for vrm-bevy-vtuber."

[dependencies]
vtuber-core = { path = "../vtuber-core" }
bevy = "=0.19.0"
bevy_vrm1 = { git = "https://github.com/not-elm/bevy_vrm1", rev = "f9593fd78136fb9e0507bcae111e09291ec9b82a", features = ["log"] }

[dev-dependencies]
bevy = { version = "=0.19.0", features = ["debug"] }

[lints]
workspace = true
